name: Sync-OneAPI-to-Aliyun1

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Git pull
      uses: actions/checkout@v3
      
    - name: Login to Docker Hub
      uses: docker/justsong/one-api@latest
      with:
        registry: registry.cn-hangzhou.aliyuncs.com
        username: adinet@aliyun.com
        password: qtmlt1989
        logout: false

 - name: Use Skopeo Tools Sync Image to Docker Hub
      run: |
         skopeo copy docker://docker.io/justsong/one-api:latest docker://registry.cn-hangzhou.aliyuncs.com/adinet/one-api:latest
      # 使用 skopeo 工具将镜像同步到阿里云个人仓库中，使用时请自行源和目标修改仓库名称和镜像名称
